#!/bin/bash

TOOLCHAIN=${HOME}/projects/openwrt/openwrt-sdk-18.06.1-ramips-mt7620_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl
STAGING_DIR=${TOOLCHAIN}/staging_dir
CROSSCOMPILE=mipsel-openwrt-linux-

export PATH=${TOOLCHAIN}/bin:${PATH}
export TOOLCHAIN
export STAGING_DIR
export CROSSCOMPILE

make $*
